LoadAsset("texture:square-dark", "assets/materials/square-dark.png")
LoadAsset("texture:square-light", "assets/materials/square-light.png")
LoadAsset("texture:white", "assets/materials/white.png")
LoadAsset("texture:black", "assets/materials/black.png")
LoadAsset("texture:restart", "assets/materials/restart.png")
LoadAsset("texture:restart-outline", "assets/materials/restart-outline.png")
LoadAsset("texture:colon", "assets/materials/colon.png")
LoadAsset("texture:0", "assets/materials/0.png")
LoadAsset("texture:1", "assets/materials/1.png")
LoadAsset("texture:2", "assets/materials/2.png")
LoadAsset("texture:3", "assets/materials/3.png")
LoadAsset("texture:4", "assets/materials/4.png")
LoadAsset("texture:5", "assets/materials/5.png")
LoadAsset("texture:6", "assets/materials/6.png")
LoadAsset("texture:7", "assets/materials/7.png")
LoadAsset("texture:8", "assets/materials/8.png")
LoadAsset("texture:9", "assets/materials/9.png")
LoadAsset("texture:cursor", "assets/materials/cursor.png")

LoadAsset("script:gamestate", "assets/scripts/gamestate.lua")
LoadAsset("script:chessboard", "assets/scripts/chessboard.lua")
LoadAsset("script:piecemoving", "assets/scripts/piecemoving.lua")
LoadAsset("script:restart", "assets/scripts/restart.lua")
LoadAsset("script:timer", "assets/scripts/timer.lua")
LoadAsset("script:turn-pointer", "assets/scripts/turn-pointer.lua")

-- Chargement des prefabs
LoadPrefab("prefab:camera", "assets/prefabs/camera.prefab")
LoadPrefab("prefab:square", "assets/prefabs/square.prefab")
LoadPrefab("prefab:chessboard", "assets/prefabs/chessboard.prefab")
LoadPrefab("prefab:pawn", "assets/prefabs/pieces/pawn.prefab")
LoadPrefab("prefab:rook", "assets/prefabs/pieces/rook.prefab")
LoadPrefab("prefab:knight", "assets/prefabs/pieces/knight.prefab")
LoadPrefab("prefab:bishop", "assets/prefabs/pieces/bishop.prefab")
LoadPrefab("prefab:queen", "assets/prefabs/pieces/queen.prefab")
LoadPrefab("prefab:king", "assets/prefabs/pieces/king.prefab")

LoadPrefab("prefab:pawn-white", "assets/prefabs/teams/pawn-white.prefab")
LoadPrefab("prefab:rook-white", "assets/prefabs/teams/rook-white.prefab")
LoadPrefab("prefab:knight-white", "assets/prefabs/teams/knight-white.prefab")
LoadPrefab("prefab:bishop-white", "assets/prefabs/teams/bishop-white.prefab")
LoadPrefab("prefab:queen-white", "assets/prefabs/teams/queen-white.prefab")
LoadPrefab("prefab:king-white", "assets/prefabs/teams/king-white.prefab")
LoadPrefab("prefab:pawn-black", "assets/prefabs/teams/pawn-black.prefab")
LoadPrefab("prefab:rook-black", "assets/prefabs/teams/rook-black.prefab")
LoadPrefab("prefab:knight-black", "assets/prefabs/teams/knight-black.prefab")
LoadPrefab("prefab:bishop-black", "assets/prefabs/teams/bishop-black.prefab")
LoadPrefab("prefab:queen-black", "assets/prefabs/teams/queen-black.prefab")
LoadPrefab("prefab:king-black", "assets/prefabs/teams/king-black.prefab")

LoadPrefab("prefab:gamestate", "assets/prefabs/gamestate.prefab")
LoadPrefab("prefab:hud-restart", "assets/prefabs/hud/restart.prefab")
LoadPrefab("prefab:hud-timer", "assets/prefabs/hud/timer.prefab")
LoadPrefab("prefab:turn-pointer", "assets/prefabs/hud/turn-pointer.prefab")

-- Contenu de la scene
GameObject.Instanciate("prefab:camera")
GameObject.Instanciate("prefab:gamestate")
GameObject.Instanciate("prefab:chessboard")
GameObject.Instanciate("prefab:hud-restart")
GameObject.Instanciate("prefab:hud-timer")
GameObject.Instanciate("prefab:turn-pointer")